import { it, describe } from "node:test";
import { strict as assert } from 'node:assert'

import { Game, resetDelay, getMap, getPlayer, isGameOver, Air, BombClose, BombReallyClose, Fire} from '../index'
import { Place, Left, Right, Up, Down } from "../index";
import { isMonsterThere, getMonster } from "../index";
import { Tile, convertToGameMap  } from '../index'

const expectedMap: Tile[][] = convertToGameMap([
      [1, 1, 1, 1, 1, 1, 1, 1, 1],
      [1, 0, 0, 2, 2, 2, 2, 2, 1],
      [1, 0, 1, 2, 1, 2, 1, 2, 1],
      [1, 2, 2, 2, 2, 2, 2, 2, 1],
      [1, 2, 1, 2, 1, 2, 1, 2, 1],
      [1, 2, 2, 2, 2, 0, 0, 0, 1],
      [1, 2, 1, 2, 1, 0, 1, 0, 1],
      [1, 2, 2, 2, 2, 0, 0, 12, 1],
      [1, 1, 1, 1, 1, 1, 1, 1, 1],
    ]);

// assert.deepStrictEqual(getMap(), [])
const gameInstance = Game.getInstance()

describe('how player kills monster with bomb', ()=>{
  it('detonates bomb at 1,2', ()=>{
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Place())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Up())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Right())
    gameInstance.update()
    resetDelay()
    gameInstance.update()
    resetDelay()
    
    assert.deepStrictEqual(getPlayer(), { x: 2, y: 1 })

    assert.ok(getMap()[2][1].isAir())
  })
  it('detonates bomb at 1,3', ()=>{
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Left())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Place())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Up())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Up())
    gameInstance.update()
    resetDelay()
    gameInstance.update()
    resetDelay()
    
    assert.deepStrictEqual(getPlayer(), { x: 1, y: 1 })

    assert.ok(getMap()[3][1].isAir())
  })
  it('detonates bomb at 1,4', ()=>{
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Place())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Up())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Up())
    gameInstance.update()
    resetDelay()
    gameInstance.update()
    resetDelay()
    
    assert.deepStrictEqual(getPlayer(), { x: 1, y: 2 })

    assert.ok(getMap()[4][1].isAir())
  })
  it('detonates bomb at 1,5', ()=>{
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Place())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Up())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Up())
    gameInstance.update()
    resetDelay()
    gameInstance.update()
    resetDelay()
    
    assert.deepStrictEqual(getPlayer(), { x: 1, y: 3 })

    assert.ok(getMap()[5][1].isAir())
  })
  it('detonates bomb at 1,6', ()=>{
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Place())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Up())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Up())
    gameInstance.update()
    resetDelay()
    gameInstance.update()
    resetDelay()
    
    assert.deepStrictEqual(getPlayer(), { x: 1, y: 4 })
    assert.ok(getMap()[6][1].isAir())
  })
  it('detonates bomb at 1,7', ()=>{
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Place())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Up())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Up())
    gameInstance.update()
    resetDelay()
    gameInstance.update()
    resetDelay()
    
    assert.deepStrictEqual(getPlayer(), { x: 1, y: 5 })

    assert.ok(getMap()[7][1].isAir())
  })
  it('detonates bomb at 2,7', ()=>{
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Right())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Place())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Left())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Up())
    gameInstance.update()
    resetDelay()
    gameInstance.update()
    resetDelay()
    
    assert.deepStrictEqual(getPlayer(), { x: 1, y: 6 })

    assert.ok(getMap()[7][2].isAir())
  })
  it('detonates bomb at 3,7', ()=>{
    Game._inputs.push(new Down())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Right())
    Game._inputs.push(new Right())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Place())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Left())
    gameInstance.update()
    resetDelay()
    Game._inputs.push(new Left())
    gameInstance.update()
    resetDelay()
    gameInstance.update()
    resetDelay()

    assert.deepStrictEqual(getPlayer(), { x: 1, y: 7 })
    assert.ok(getMap()[7][4].isAir())
  })
  it('expected that monster is at 7,6', ()=>{
    assert.ok(isMonsterThere())
    assert.deepStrictEqual(getMonster(), {x:7, y:6})
  })
  it('expected that player is at 5,7', ()=>{
    Game._inputs.push(new Right())
    Game._inputs.push(new Right())
    Game._inputs.push(new Right())
    Game._inputs.push(new Right())
    gameInstance.update()
    resetDelay()
    assert.deepStrictEqual(getPlayer(), { x: 5, y: 7 })
  })

  it('expected that monster is at 7,7', ()=>{
    assert.ok(isMonsterThere())
    assert.deepStrictEqual(getMonster(), {x:7, y:7})
  })
  it('expected that bomb is at 5,7 and player is at 3,7', ()=>{
    Game._inputs.push(new Place())
    gameInstance.update()
    Game._inputs.push(new Left())
    gameInstance.update()
    Game._inputs.push(new Left())
    gameInstance.update()
    resetDelay()
    assert.deepStrictEqual(getPlayer(), { x: 3, y: 7 })
  })
  it('expected that monster is at 7,7', ()=>{
    assert.ok(isMonsterThere())
    assert.deepStrictEqual(getMonster(), {x:7, y:7})
  })
  it('expected that bomb is at 5,7', ()=>{
    assert.ok(getMap()[7][5].isBombClose())
  })
  it('expected that bomb is BOMB_REALLY_CLOSE)', ()=>{
    gameInstance.update()
    resetDelay()
    assert.ok(getMap()[7][5].isBombReallyClose())
  })
  it('expected that monster is at 6,7', ()=>{
    assert.ok(isMonsterThere())
    assert.deepStrictEqual(getMonster(), {x:6, y:7})
  })

  it('expected that FIRE is at 5,7, 4,7 ans 3,7)', ()=>{
    gameInstance.update()
    resetDelay()
    assert.ok(getMap()[7][6].isFire(), `getMap()[7][6] ${getMap()[7][6]}`)
    assert.ok(getMap()[7][5].isFire(), `getMap()[7][5] ${getMap()[7][5]}`)
    assert.ok(getMap()[7][4].isFire(), `getMap()[7][4] ${getMap()[7][4]}`)
  })

  it('should be game over after monster is eaten by fire but it is not', ()=>{
    gameInstance.update()
    resetDelay()
    gameInstance.update()
    resetDelay()
    gameInstance.update()
    resetDelay()
    assert.strictEqual(isGameOver(), false)

    assert.ok(!isMonsterThere())
  })

})